#######################################################################################
# Book settings
title: Score Models # The title of the book. Will be placed in the left navbar.
author: Alexandre Adam # The author of the book
copyright: "2023" # Copyright year to be placed in the footer
#logo                        : "figures/milex_logo_cyber.png"  # A path to the book logo
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
# Auto-exclude files not in the toc
only_build_toc_files: true 

#######################################################################################
# HTML-specific settings
html:
  #favicon                   : ""  # A path to a favicon image
  use_edit_page_button: false # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button: true # Whether to add a link to your repository button
  use_issues_button: true # Whether to add an "open an issue" button
  use_multitoc_numbering: true # Continuous numbering across parts/chapters
  #extra_footer              : ""  # Will be displayed underneath the footer.
  #google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar: true # Whether to include your home page in the left Navigation Bar
  #baseurl                   : ""  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  #analytics:
  #plausible_analytics_url: https://plausible.io/js/script.js

  comments:
    hypothesis: false
    utterances: false
  announcement: "" # A banner announcement at the top of the site.
  
#######################################################################################
# Launch button settings
#launch_buttons:
#notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
#binderhub_url             : ""  # The URL of the BinderHub (e.g., https://mybinder.org)
#jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
#thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
#colab_url                 : "" # The URL of Google Colab (https://colab.research.google.com)

repository:
  url: https://github.com/AlexandreAdam/score_models # The URL to your book's repository
  path_to_book: "docs/" # A path to your book's folder, relative to the repository root.
  branch: master # Which branch of the repository should be used when creating links

#######################################################################################

